// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package testing

import (
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *LongString) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return err
	}

	// t.Val (string) (string)
	if len(t.Val) > 10000 {
		return fmt.Errorf("Value in field t.Val was too long")
	}
	if err := jw.WriteString(string(t.Val)); err != nil {
		return err
	}
	if err := jw.WriteArrayClose(); err != nil {
		return err
	}
	return nil
}

func (t *LongString) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = LongString{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return err
	}

	// t.Val (string) (string)

	{
		sval, err := jr.ReadString(10000)
		if err != nil {
			return err
		}
		t.Val = string(sval)
	}
	if err := jr.ReadArrayClose(); err != nil {
		return err
	}
	return nil
}
