// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package testing

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *SimpleTypeTree) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.BoolPtr (bool) (bool)
	if len("BoolPtr") > 8192 {
		return fmt.Errorf("string in field \"BoolPtr\" was too long")
	}
	if err := jw.WriteString(string("BoolPtr")); err != nil {
		return fmt.Errorf("writing string for field \"BoolPtr\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if t.BoolPtr == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.BoolPtr: %w", err)
		}
	} else {
		if err := jw.WriteBool(*t.BoolPtr); err != nil {
			return fmt.Errorf("writing bool for field t.BoolPtr: %w", err)
		}
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Dog (string) (string)
	if len("Dog") > 8192 {
		return fmt.Errorf("string in field \"Dog\" was too long")
	}
	if err := jw.WriteString(string("Dog")); err != nil {
		return fmt.Errorf("writing string for field \"Dog\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Dog) > 8192 {
		return fmt.Errorf("string in field t.Dog was too long")
	}
	if err := jw.WriteString(string(t.Dog)); err != nil {
		return fmt.Errorf("writing string for field t.Dog: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.NotPizza (uint64) (uint64)
	if len("NotPizza") > 8192 {
		return fmt.Errorf("string in field \"NotPizza\" was too long")
	}
	if err := jw.WriteString(string("NotPizza")); err != nil {
		return fmt.Errorf("writing string for field \"NotPizza\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if t.NotPizza == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.NotPizza: %w", err)
		}
	} else {
		if err := jw.WriteUint64(uint64(*t.NotPizza)); err != nil {
			return fmt.Errorf("writing uint64 for field t.NotPizza: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Others ([]uint64) (slice)
	if len("Others") > 8192 {
		return fmt.Errorf("string in field \"Others\" was too long")
	}
	if err := jw.WriteString(string("Others")); err != nil {
		return fmt.Errorf("writing string for field \"Others\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Others) > 8192 {
		return fmt.Errorf("slice value in field t.Others was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Others: %w", err)
	}
	for i, v := range t.Others {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Others: %w", err)
			}
		}

		if err := jw.WriteUint64(uint64(v)); err != nil {
			return fmt.Errorf("writing uint64 for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Others: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.SixtyThreeBitIntegerWithASignBit (int64) (int64)
	if len("SixtyThreeBitIntegerWithASignBit") > 8192 {
		return fmt.Errorf("string in field \"SixtyThreeBitIntegerWithASignBit\" was too long")
	}
	if err := jw.WriteString(string("SixtyThreeBitIntegerWithASignBit")); err != nil {
		return fmt.Errorf("writing string for field \"SixtyThreeBitIntegerWithASignBit\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.SixtyThreeBitIntegerWithASignBit)); err != nil {
		return fmt.Errorf("writing int64 for field t.SixtyThreeBitIntegerWithASignBit: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.StringPtr (string) (string)
	if len("StringPtr") > 8192 {
		return fmt.Errorf("string in field \"StringPtr\" was too long")
	}
	if err := jw.WriteString(string("StringPtr")); err != nil {
		return fmt.Errorf("writing string for field \"StringPtr\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if t.StringPtr == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.StringPtr: %w", err)
		}
	} else {
		if len(*t.StringPtr) > 8192 {
			return fmt.Errorf("string in field t.StringPtr was too long")
		}
		if err := jw.WriteString(string(*t.StringPtr)); err != nil {
			return fmt.Errorf("writing string for field t.StringPtr: %w", err)
		}
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Stuff (testing.SimpleTypeTree) (struct)
	if len("Stuff") > 8192 {
		return fmt.Errorf("string in field \"Stuff\" was too long")
	}
	if err := jw.WriteString(string("Stuff")); err != nil {
		return fmt.Errorf("writing string for field \"Stuff\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Stuff.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Stuff: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Stufff (testing.SimpleTypeTwo) (struct)
	if len("Stufff") > 8192 {
		return fmt.Errorf("string in field \"Stufff\" was too long")
	}
	if err := jw.WriteString(string("Stufff")); err != nil {
		return fmt.Errorf("writing string for field \"Stufff\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Stufff.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Stufff: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Test ([][]uint8) (slice)
	if len("Test") > 8192 {
		return fmt.Errorf("string in field \"Test\" was too long")
	}
	if err := jw.WriteString(string("Test")); err != nil {
		return fmt.Errorf("writing string for field \"Test\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Test) > 8192 {
		return fmt.Errorf("slice value in field t.Test was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Test: %w", err)
	}
	for i, v := range t.Test {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Test: %w", err)
			}
		}
		if len(v) > 2097152 {
			return fmt.Errorf("byte array in field v was too long")
		}

		if err := jw.WriteBytes(v); err != nil {
			return fmt.Errorf("writing bytes for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Test: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *SimpleTypeTree) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = SimpleTypeTree{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for SimpleTypeTree: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for SimpleTypeTree: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for SimpleTypeTree: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field SimpleTypeTree: string too large")
				}
				return fmt.Errorf("reading string for field SimpleTypeTree: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field SimpleTypeTree: %w", err)
			}
			switch name {

			// t.BoolPtr (bool) (bool)
			case "BoolPtr":
				{
					bval, err := jr.ReadBoolOrNull()
					if err != nil {
						return fmt.Errorf("reading bool or null for field t.BoolPtr: %w", err)
					}
					if bval != nil {
						t.BoolPtr = bval
					}
				}

				// t.Dog (string) (string)
			case "Dog":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Dog: string too long")
						}
						return fmt.Errorf("reading string for field t.Dog: %w", err)
					}
					t.Dog = string(sval)
				}

				// t.NotPizza (uint64) (uint64)
			case "NotPizza":
				{

					nval, err := jr.ReadNumberAsUint64OrNull()
					if err != nil {
						return fmt.Errorf("reading uint64 or null for field t.NotPizza: %w", err)
					}
					if nval != nil {
						typed := uint64(*nval)
						t.NotPizza = &typed
					}

				}

				// t.Others ([]uint64) (slice)
			case "Others":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Others: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Others: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Others: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]uint64, 1)
							{

								nval, err := jr.ReadNumberAsUint64()
								if err != nil {
									return fmt.Errorf("reading uint64 for field item[0]: %w", err)
								}
								item[0] = uint64(nval)

							}
							t.Others = append(t.Others, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Others: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Others: slice too large")
							}
						}
					}

				}

				// t.SixtyThreeBitIntegerWithASignBit (int64) (int64)
			case "SixtyThreeBitIntegerWithASignBit":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.SixtyThreeBitIntegerWithASignBit: %w", err)
					}
					t.SixtyThreeBitIntegerWithASignBit = int64(nval)

				}

				// t.StringPtr (string) (string)
			case "StringPtr":
				{
					sval, err := jr.ReadStringOrNull(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string or null for field t.StringPtr: string too long")
						}
						return fmt.Errorf("reading string or null for field t.StringPtr: %w", err)
					}
					if sval != nil {
						t.StringPtr = (*string)(sval)
					}
				}

				// t.Stuff (testing.SimpleTypeTree) (struct)
			case "Stuff":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("peeking null for field t.Stuff: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("reading null for field t.Stuff: %w", err)
						}
					} else {
						t.Stuff = new(SimpleTypeTree)
						if err := t.Stuff.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Stuff pointer: %w", err)
						}
					}
				}

				// t.Stufff (testing.SimpleTypeTwo) (struct)
			case "Stufff":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("peeking null for field t.Stufff: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("reading null for field t.Stufff: %w", err)
						}
					} else {
						t.Stufff = new(SimpleTypeTwo)
						if err := t.Stufff.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Stufff pointer: %w", err)
						}
					}
				}

				// t.Test ([][]uint8) (slice)
			case "Test":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Test: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Test: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Test: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([][]uint8, 1)

							{
								bval, err := jr.ReadBytes(2097152)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading bytes for field item[0]: byte array too large")
									}
									return fmt.Errorf("reading bytes for field item[0]: %w", err)
								}
								if len(bval) > 0 {
									item[0] = []uint8(bval)
								}
							}

							t.Test = append(t.Test, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Test: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Test: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for SimpleTypeTree: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field SimpleTypeTree: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for SimpleTypeTree")
			}
		}
	}

	return nil
}
func (t *NeedScratchForMap) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Thing (bool) (bool)
	if len("Thing") > 8192 {
		return fmt.Errorf("string in field \"Thing\" was too long")
	}
	if err := jw.WriteString(string("Thing")); err != nil {
		return fmt.Errorf("writing string for field \"Thing\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := jw.WriteBool(t.Thing); err != nil {
		return fmt.Errorf("writing bool for field t.Thing: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *NeedScratchForMap) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = NeedScratchForMap{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for NeedScratchForMap: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for NeedScratchForMap: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for NeedScratchForMap: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field NeedScratchForMap: string too large")
				}
				return fmt.Errorf("reading string for field NeedScratchForMap: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field NeedScratchForMap: %w", err)
			}
			switch name {

			// t.Thing (bool) (bool)
			case "Thing":
				bval, err := jr.ReadBool()
				if err != nil {
					return fmt.Errorf("reading bool for field t.Thing: %w", err)
				}
				t.Thing = bval
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for NeedScratchForMap: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field NeedScratchForMap: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for NeedScratchForMap")
			}
		}
	}

	return nil
}
func (t *SimpleStructV1) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.OldArray ([]testing.SimpleTypeOne) (slice)
	if len("OldArray") > 8192 {
		return fmt.Errorf("string in field \"OldArray\" was too long")
	}
	if err := jw.WriteString(string("OldArray")); err != nil {
		return fmt.Errorf("writing string for field \"OldArray\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.OldArray) > 8192 {
		return fmt.Errorf("slice value in field t.OldArray was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.OldArray: %w", err)
	}
	for i, v := range t.OldArray {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.OldArray: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.OldArray: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldBytes ([]uint8) (slice)
	if len("OldBytes") > 8192 {
		return fmt.Errorf("string in field \"OldBytes\" was too long")
	}
	if err := jw.WriteString(string("OldBytes")); err != nil {
		return fmt.Errorf("writing string for field \"OldBytes\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.OldBytes) > 2097152 {
		return fmt.Errorf("byte array in field t.OldBytes was too long")
	}

	if err := jw.WriteBytes(t.OldBytes); err != nil {
		return fmt.Errorf("writing bytes for field t.OldBytes: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldCidArray ([]cid.Cid) (slice)
	if len("OldCidArray") > 8192 {
		return fmt.Errorf("string in field \"OldCidArray\" was too long")
	}
	if err := jw.WriteString(string("OldCidArray")); err != nil {
		return fmt.Errorf("writing string for field \"OldCidArray\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.OldCidArray) > 8192 {
		return fmt.Errorf("slice value in field t.OldCidArray was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.OldCidArray: %w", err)
	}
	for i, v := range t.OldCidArray {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.OldCidArray: %w", err)
			}
		}

		if err := jw.WriteCid(v); err != nil {
			return fmt.Errorf("writing CID for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.OldCidArray: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldCidPtrArray ([]*cid.Cid) (slice)
	if len("OldCidPtrArray") > 8192 {
		return fmt.Errorf("string in field \"OldCidPtrArray\" was too long")
	}
	if err := jw.WriteString(string("OldCidPtrArray")); err != nil {
		return fmt.Errorf("writing string for field \"OldCidPtrArray\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.OldCidPtrArray) > 8192 {
		return fmt.Errorf("slice value in field t.OldCidPtrArray was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.OldCidPtrArray: %w", err)
	}
	for i, v := range t.OldCidPtrArray {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.OldCidPtrArray: %w", err)
			}
		}

		if v == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("writing null for field v: %w", err)
			}
		} else {
			if err := jw.WriteCid(*v); err != nil {
				return fmt.Errorf("writing CID for field v: %w", err)
			}
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.OldCidPtrArray: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldMap (map[string]testing.SimpleTypeOne) (map)
	if len("OldMap") > 8192 {
		return fmt.Errorf("string in field \"OldMap\" was too long")
	}
	if err := jw.WriteString(string("OldMap")); err != nil {
		return fmt.Errorf("writing string for field \"OldMap\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.OldMap) > 4096 {
			return fmt.Errorf("cannot marshal t.OldMap map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.OldMap: %w", err)
		}

		keys := make([]string, 0, len(t.OldMap))
		for k := range t.OldMap {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.OldMap: %w", err)
				}
			}
			v := t.OldMap[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.OldMap: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.OldMap: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldNum (uint64) (uint64)
	if len("OldNum") > 8192 {
		return fmt.Errorf("string in field \"OldNum\" was too long")
	}
	if err := jw.WriteString(string("OldNum")); err != nil {
		return fmt.Errorf("writing string for field \"OldNum\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.OldNum)); err != nil {
		return fmt.Errorf("writing uint64 for field t.OldNum: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldPtr (cid.Cid) (struct)
	if len("OldPtr") > 8192 {
		return fmt.Errorf("string in field \"OldPtr\" was too long")
	}
	if err := jw.WriteString(string("OldPtr")); err != nil {
		return fmt.Errorf("writing string for field \"OldPtr\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if t.OldPtr == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.OldPtr: %w", err)
		}
	} else {
		if err := jw.WriteCid(*t.OldPtr); err != nil {
			return fmt.Errorf("writing CID for field t.OldPtr: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldStr (string) (string)
	if len("OldStr") > 8192 {
		return fmt.Errorf("string in field \"OldStr\" was too long")
	}
	if err := jw.WriteString(string("OldStr")); err != nil {
		return fmt.Errorf("writing string for field \"OldStr\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.OldStr) > 8192 {
		return fmt.Errorf("string in field t.OldStr was too long")
	}
	if err := jw.WriteString(string(t.OldStr)); err != nil {
		return fmt.Errorf("writing string for field t.OldStr: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldStruct (testing.SimpleTypeOne) (struct)
	if len("OldStruct") > 8192 {
		return fmt.Errorf("string in field \"OldStruct\" was too long")
	}
	if err := jw.WriteString(string("OldStruct")); err != nil {
		return fmt.Errorf("writing string for field \"OldStruct\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.OldStruct.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.OldStruct: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *SimpleStructV1) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = SimpleStructV1{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for SimpleStructV1: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for SimpleStructV1: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for SimpleStructV1: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field SimpleStructV1: string too large")
				}
				return fmt.Errorf("reading string for field SimpleStructV1: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field SimpleStructV1: %w", err)
			}
			switch name {

			// t.OldArray ([]testing.SimpleTypeOne) (slice)
			case "OldArray":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.OldArray: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.OldArray: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.OldArray: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]SimpleTypeOne, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.OldArray = append(t.OldArray, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.OldArray: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.OldArray: slice too large")
							}
						}
					}

				}

				// t.OldBytes ([]uint8) (slice)
			case "OldBytes":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.OldBytes: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.OldBytes: %w", err)
					}
					if len(bval) > 0 {
						t.OldBytes = []uint8(bval)
					}
				}

				// t.OldCidArray ([]cid.Cid) (slice)
			case "OldCidArray":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.OldCidArray: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.OldCidArray: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.OldCidArray: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]cid.Cid, 1)
							{

								c, err := jr.ReadCid()
								if err != nil {
									return fmt.Errorf("reading CID for field item[0]: %w", err)
								}
								item[0] = c

							}
							t.OldCidArray = append(t.OldCidArray, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.OldCidArray: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.OldCidArray: slice too large")
							}
						}
					}

				}

				// t.OldCidPtrArray ([]*cid.Cid) (slice)
			case "OldCidPtrArray":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.OldCidPtrArray: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.OldCidPtrArray: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.OldCidPtrArray: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]*cid.Cid, 1)
							{

								c, err := jr.ReadCidOrNull()
								if err != nil {
									return fmt.Errorf("reading CID or null for field item[0]: %w", err)
								}
								item[0] = c

							}
							t.OldCidPtrArray = append(t.OldCidPtrArray, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.OldCidPtrArray: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.OldCidPtrArray: slice too large")
							}
						}
					}

				}

				// t.OldMap (map[string]testing.SimpleTypeOne) (map)
			case "OldMap":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.OldMap: %w", err)
				}

				t.OldMap = map[string]SimpleTypeOne{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.OldMap: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.OldMap: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.OldMap: %w", err)
						}
						var v SimpleTypeOne

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.OldMap[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.OldMap: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.OldNum (uint64) (uint64)
			case "OldNum":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.OldNum: %w", err)
					}
					t.OldNum = uint64(nval)

				}

				// t.OldPtr (cid.Cid) (struct)
			case "OldPtr":
				{

					c, err := jr.ReadCidOrNull()
					if err != nil {
						return fmt.Errorf("reading CID or null for field t.OldPtr: %w", err)
					}
					t.OldPtr = c

				}

				// t.OldStr (string) (string)
			case "OldStr":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.OldStr: string too long")
						}
						return fmt.Errorf("reading string for field t.OldStr: %w", err)
					}
					t.OldStr = string(sval)
				}

				// t.OldStruct (testing.SimpleTypeOne) (struct)
			case "OldStruct":

				if err := t.OldStruct.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.OldStruct: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for SimpleStructV1: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field SimpleStructV1: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for SimpleStructV1")
			}
		}
	}

	return nil
}
func (t *SimpleStructV2) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.NewArray ([]testing.SimpleTypeOne) (slice)
	if len("NewArray") > 8192 {
		return fmt.Errorf("string in field \"NewArray\" was too long")
	}
	if err := jw.WriteString(string("NewArray")); err != nil {
		return fmt.Errorf("writing string for field \"NewArray\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.NewArray) > 8192 {
		return fmt.Errorf("slice value in field t.NewArray was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.NewArray: %w", err)
	}
	for i, v := range t.NewArray {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.NewArray: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.NewArray: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.NewBytes ([]uint8) (slice)
	if len("NewBytes") > 8192 {
		return fmt.Errorf("string in field \"NewBytes\" was too long")
	}
	if err := jw.WriteString(string("NewBytes")); err != nil {
		return fmt.Errorf("writing string for field \"NewBytes\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.NewBytes) > 2097152 {
		return fmt.Errorf("byte array in field t.NewBytes was too long")
	}

	if err := jw.WriteBytes(t.NewBytes); err != nil {
		return fmt.Errorf("writing bytes for field t.NewBytes: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.NewMap (map[string]testing.SimpleTypeOne) (map)
	if len("NewMap") > 8192 {
		return fmt.Errorf("string in field \"NewMap\" was too long")
	}
	if err := jw.WriteString(string("NewMap")); err != nil {
		return fmt.Errorf("writing string for field \"NewMap\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.NewMap) > 4096 {
			return fmt.Errorf("cannot marshal t.NewMap map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.NewMap: %w", err)
		}

		keys := make([]string, 0, len(t.NewMap))
		for k := range t.NewMap {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.NewMap: %w", err)
				}
			}
			v := t.NewMap[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.NewMap: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.NewMap: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.NewNum (uint64) (uint64)
	if len("NewNum") > 8192 {
		return fmt.Errorf("string in field \"NewNum\" was too long")
	}
	if err := jw.WriteString(string("NewNum")); err != nil {
		return fmt.Errorf("writing string for field \"NewNum\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.NewNum)); err != nil {
		return fmt.Errorf("writing uint64 for field t.NewNum: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.NewPtr (cid.Cid) (struct)
	if len("NewPtr") > 8192 {
		return fmt.Errorf("string in field \"NewPtr\" was too long")
	}
	if err := jw.WriteString(string("NewPtr")); err != nil {
		return fmt.Errorf("writing string for field \"NewPtr\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if t.NewPtr == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.NewPtr: %w", err)
		}
	} else {
		if err := jw.WriteCid(*t.NewPtr); err != nil {
			return fmt.Errorf("writing CID for field t.NewPtr: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.NewStr (string) (string)
	if len("NewStr") > 8192 {
		return fmt.Errorf("string in field \"NewStr\" was too long")
	}
	if err := jw.WriteString(string("NewStr")); err != nil {
		return fmt.Errorf("writing string for field \"NewStr\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.NewStr) > 8192 {
		return fmt.Errorf("string in field t.NewStr was too long")
	}
	if err := jw.WriteString(string(t.NewStr)); err != nil {
		return fmt.Errorf("writing string for field t.NewStr: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.NewStruct (testing.SimpleTypeOne) (struct)
	if len("NewStruct") > 8192 {
		return fmt.Errorf("string in field \"NewStruct\" was too long")
	}
	if err := jw.WriteString(string("NewStruct")); err != nil {
		return fmt.Errorf("writing string for field \"NewStruct\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.NewStruct.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.NewStruct: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldArray ([]testing.SimpleTypeOne) (slice)
	if len("OldArray") > 8192 {
		return fmt.Errorf("string in field \"OldArray\" was too long")
	}
	if err := jw.WriteString(string("OldArray")); err != nil {
		return fmt.Errorf("writing string for field \"OldArray\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.OldArray) > 8192 {
		return fmt.Errorf("slice value in field t.OldArray was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.OldArray: %w", err)
	}
	for i, v := range t.OldArray {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.OldArray: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.OldArray: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldBytes ([]uint8) (slice)
	if len("OldBytes") > 8192 {
		return fmt.Errorf("string in field \"OldBytes\" was too long")
	}
	if err := jw.WriteString(string("OldBytes")); err != nil {
		return fmt.Errorf("writing string for field \"OldBytes\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.OldBytes) > 2097152 {
		return fmt.Errorf("byte array in field t.OldBytes was too long")
	}

	if err := jw.WriteBytes(t.OldBytes); err != nil {
		return fmt.Errorf("writing bytes for field t.OldBytes: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldMap (map[string]testing.SimpleTypeOne) (map)
	if len("OldMap") > 8192 {
		return fmt.Errorf("string in field \"OldMap\" was too long")
	}
	if err := jw.WriteString(string("OldMap")); err != nil {
		return fmt.Errorf("writing string for field \"OldMap\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.OldMap) > 4096 {
			return fmt.Errorf("cannot marshal t.OldMap map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.OldMap: %w", err)
		}

		keys := make([]string, 0, len(t.OldMap))
		for k := range t.OldMap {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.OldMap: %w", err)
				}
			}
			v := t.OldMap[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.OldMap: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.OldMap: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldNum (uint64) (uint64)
	if len("OldNum") > 8192 {
		return fmt.Errorf("string in field \"OldNum\" was too long")
	}
	if err := jw.WriteString(string("OldNum")); err != nil {
		return fmt.Errorf("writing string for field \"OldNum\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.OldNum)); err != nil {
		return fmt.Errorf("writing uint64 for field t.OldNum: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldPtr (cid.Cid) (struct)
	if len("OldPtr") > 8192 {
		return fmt.Errorf("string in field \"OldPtr\" was too long")
	}
	if err := jw.WriteString(string("OldPtr")); err != nil {
		return fmt.Errorf("writing string for field \"OldPtr\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if t.OldPtr == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.OldPtr: %w", err)
		}
	} else {
		if err := jw.WriteCid(*t.OldPtr); err != nil {
			return fmt.Errorf("writing CID for field t.OldPtr: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldStr (string) (string)
	if len("OldStr") > 8192 {
		return fmt.Errorf("string in field \"OldStr\" was too long")
	}
	if err := jw.WriteString(string("OldStr")); err != nil {
		return fmt.Errorf("writing string for field \"OldStr\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.OldStr) > 8192 {
		return fmt.Errorf("string in field t.OldStr was too long")
	}
	if err := jw.WriteString(string(t.OldStr)); err != nil {
		return fmt.Errorf("writing string for field t.OldStr: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.OldStruct (testing.SimpleTypeOne) (struct)
	if len("OldStruct") > 8192 {
		return fmt.Errorf("string in field \"OldStruct\" was too long")
	}
	if err := jw.WriteString(string("OldStruct")); err != nil {
		return fmt.Errorf("writing string for field \"OldStruct\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.OldStruct.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.OldStruct: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *SimpleStructV2) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = SimpleStructV2{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for SimpleStructV2: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for SimpleStructV2: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for SimpleStructV2: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field SimpleStructV2: string too large")
				}
				return fmt.Errorf("reading string for field SimpleStructV2: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field SimpleStructV2: %w", err)
			}
			switch name {

			// t.NewArray ([]testing.SimpleTypeOne) (slice)
			case "NewArray":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.NewArray: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.NewArray: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.NewArray: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]SimpleTypeOne, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.NewArray = append(t.NewArray, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.NewArray: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.NewArray: slice too large")
							}
						}
					}

				}

				// t.NewBytes ([]uint8) (slice)
			case "NewBytes":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.NewBytes: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.NewBytes: %w", err)
					}
					if len(bval) > 0 {
						t.NewBytes = []uint8(bval)
					}
				}

				// t.NewMap (map[string]testing.SimpleTypeOne) (map)
			case "NewMap":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.NewMap: %w", err)
				}

				t.NewMap = map[string]SimpleTypeOne{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.NewMap: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.NewMap: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.NewMap: %w", err)
						}
						var v SimpleTypeOne

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.NewMap[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.NewMap: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.NewNum (uint64) (uint64)
			case "NewNum":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.NewNum: %w", err)
					}
					t.NewNum = uint64(nval)

				}

				// t.NewPtr (cid.Cid) (struct)
			case "NewPtr":
				{

					c, err := jr.ReadCidOrNull()
					if err != nil {
						return fmt.Errorf("reading CID or null for field t.NewPtr: %w", err)
					}
					t.NewPtr = c

				}

				// t.NewStr (string) (string)
			case "NewStr":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.NewStr: string too long")
						}
						return fmt.Errorf("reading string for field t.NewStr: %w", err)
					}
					t.NewStr = string(sval)
				}

				// t.NewStruct (testing.SimpleTypeOne) (struct)
			case "NewStruct":

				if err := t.NewStruct.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.NewStruct: %w", err)
				}

				// t.OldArray ([]testing.SimpleTypeOne) (slice)
			case "OldArray":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.OldArray: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.OldArray: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.OldArray: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]SimpleTypeOne, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.OldArray = append(t.OldArray, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.OldArray: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.OldArray: slice too large")
							}
						}
					}

				}

				// t.OldBytes ([]uint8) (slice)
			case "OldBytes":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.OldBytes: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.OldBytes: %w", err)
					}
					if len(bval) > 0 {
						t.OldBytes = []uint8(bval)
					}
				}

				// t.OldMap (map[string]testing.SimpleTypeOne) (map)
			case "OldMap":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.OldMap: %w", err)
				}

				t.OldMap = map[string]SimpleTypeOne{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.OldMap: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.OldMap: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.OldMap: %w", err)
						}
						var v SimpleTypeOne

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.OldMap[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.OldMap: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.OldNum (uint64) (uint64)
			case "OldNum":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.OldNum: %w", err)
					}
					t.OldNum = uint64(nval)

				}

				// t.OldPtr (cid.Cid) (struct)
			case "OldPtr":
				{

					c, err := jr.ReadCidOrNull()
					if err != nil {
						return fmt.Errorf("reading CID or null for field t.OldPtr: %w", err)
					}
					t.OldPtr = c

				}

				// t.OldStr (string) (string)
			case "OldStr":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.OldStr: string too long")
						}
						return fmt.Errorf("reading string for field t.OldStr: %w", err)
					}
					t.OldStr = string(sval)
				}

				// t.OldStruct (testing.SimpleTypeOne) (struct)
			case "OldStruct":

				if err := t.OldStruct.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.OldStruct: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for SimpleStructV2: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field SimpleStructV2: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for SimpleStructV2")
			}
		}
	}

	return nil
}
func (t *RenamedFields) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Bar (string) (string)
	if len("beep") > 8192 {
		return fmt.Errorf("string in field \"beep\" was too long")
	}
	if err := jw.WriteString(string("beep")); err != nil {
		return fmt.Errorf("writing string for field \"beep\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Bar) > 8192 {
		return fmt.Errorf("string in field t.Bar was too long")
	}
	if err := jw.WriteString(string(t.Bar)); err != nil {
		return fmt.Errorf("writing string for field t.Bar: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Foo (int64) (int64)
	if len("foo") > 8192 {
		return fmt.Errorf("string in field \"foo\" was too long")
	}
	if err := jw.WriteString(string("foo")); err != nil {
		return fmt.Errorf("writing string for field \"foo\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Foo)); err != nil {
		return fmt.Errorf("writing int64 for field t.Foo: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RenamedFields) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RenamedFields{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for RenamedFields: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for RenamedFields: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for RenamedFields: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field RenamedFields: string too large")
				}
				return fmt.Errorf("reading string for field RenamedFields: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field RenamedFields: %w", err)
			}
			switch name {

			// t.Bar (string) (string)
			case "beep":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Bar: string too long")
						}
						return fmt.Errorf("reading string for field t.Bar: %w", err)
					}
					t.Bar = string(sval)
				}

				// t.Foo (int64) (int64)
			case "foo":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Foo: %w", err)
					}
					t.Foo = int64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for RenamedFields: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field RenamedFields: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for RenamedFields")
			}
		}
	}

	return nil
}
func (t *TestEmpty) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Beep (string) (string)
	if t.Beep != "" {
		if len("Beep") > 8192 {
			return fmt.Errorf("string in field \"Beep\" was too long")
		}
		if err := jw.WriteString(string("Beep")); err != nil {
			return fmt.Errorf("writing string for field \"Beep\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if len(t.Beep) > 8192 {
			return fmt.Errorf("string in field t.Beep was too long")
		}
		if err := jw.WriteString(string(t.Beep)); err != nil {
			return fmt.Errorf("writing string for field t.Beep: %w", err)
		}
		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cat (int64) (int64)
	if len("Cat") > 8192 {
		return fmt.Errorf("string in field \"Cat\" was too long")
	}
	if err := jw.WriteString(string("Cat")); err != nil {
		return fmt.Errorf("writing string for field \"Cat\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Cat)); err != nil {
		return fmt.Errorf("writing int64 for field t.Cat: %w", err)
	}

	written++
	if t.Foo != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Foo (string) (string)
	if t.Foo != nil {
		if len("Foo") > 8192 {
			return fmt.Errorf("string in field \"Foo\" was too long")
		}
		if err := jw.WriteString(string("Foo")); err != nil {
			return fmt.Errorf("writing string for field \"Foo\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if t.Foo == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("writing null for field t.Foo: %w", err)
			}
		} else {
			if len(*t.Foo) > 8192 {
				return fmt.Errorf("string in field t.Foo was too long")
			}
			if err := jw.WriteString(string(*t.Foo)); err != nil {
				return fmt.Errorf("writing string for field t.Foo: %w", err)
			}
		}
		written++
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *TestEmpty) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = TestEmpty{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for TestEmpty: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for TestEmpty: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for TestEmpty: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field TestEmpty: string too large")
				}
				return fmt.Errorf("reading string for field TestEmpty: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field TestEmpty: %w", err)
			}
			switch name {

			// t.Beep (string) (string)
			case "Beep":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Beep: string too long")
						}
						return fmt.Errorf("reading string for field t.Beep: %w", err)
					}
					t.Beep = string(sval)
				}

				// t.Cat (int64) (int64)
			case "Cat":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Cat: %w", err)
					}
					t.Cat = int64(nval)

				}

				// t.Foo (string) (string)
			case "Foo":
				{
					sval, err := jr.ReadStringOrNull(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string or null for field t.Foo: string too long")
						}
						return fmt.Errorf("reading string or null for field t.Foo: %w", err)
					}
					if sval != nil {
						t.Foo = (*string)(sval)
					}
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for TestEmpty: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field TestEmpty: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for TestEmpty")
			}
		}
	}

	return nil
}
func (t *TestConstField) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Cats (string) (string)
	if len("Cats") > 8192 {
		return fmt.Errorf("string in field \"Cats\" was too long")
	}
	if err := jw.WriteString(string("Cats")); err != nil {
		return fmt.Errorf("writing string for field \"Cats\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := jw.WriteString("dogsdrool"); err != nil {
		return err
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Thing (int64) (int64)
	if len("Thing") > 8192 {
		return fmt.Errorf("string in field \"Thing\" was too long")
	}
	if err := jw.WriteString(string("Thing")); err != nil {
		return fmt.Errorf("writing string for field \"Thing\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Thing)); err != nil {
		return fmt.Errorf("writing int64 for field t.Thing: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *TestConstField) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = TestConstField{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for TestConstField: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for TestConstField: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for TestConstField: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field TestConstField: string too large")
				}
				return fmt.Errorf("reading string for field TestConstField: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field TestConstField: %w", err)
			}
			switch name {

			// t.Cats (string) (string)
			case "Cats":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Cats: string too long")
						}
						return fmt.Errorf("reading string for field t.Cats: %w", err)
					}
					t.Cats = string(sval)
				}

				// t.Thing (int64) (int64)
			case "Thing":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Thing: %w", err)
					}
					t.Thing = int64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for TestConstField: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field TestConstField: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for TestConstField")
			}
		}
	}

	return nil
}
func (t *TestCanonicalFieldOrder) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Drond (int64) (int64)
	if len("Drond") > 8192 {
		return fmt.Errorf("string in field \"Drond\" was too long")
	}
	if err := jw.WriteString(string("Drond")); err != nil {
		return fmt.Errorf("writing string for field \"Drond\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Drond)); err != nil {
		return fmt.Errorf("writing int64 for field t.Drond: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Zp (string) (string)
	if len("ap") > 8192 {
		return fmt.Errorf("string in field \"ap\" was too long")
	}
	if err := jw.WriteString(string("ap")); err != nil {
		return fmt.Errorf("writing string for field \"ap\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Zp) > 8192 {
		return fmt.Errorf("string in field t.Zp was too long")
	}
	if err := jw.WriteString(string(t.Zp)); err != nil {
		return fmt.Errorf("writing string for field t.Zp: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Bar (string) (string)
	if len("beep") > 8192 {
		return fmt.Errorf("string in field \"beep\" was too long")
	}
	if err := jw.WriteString(string("beep")); err != nil {
		return fmt.Errorf("writing string for field \"beep\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Bar) > 8192 {
		return fmt.Errorf("string in field t.Bar was too long")
	}
	if err := jw.WriteString(string(t.Bar)); err != nil {
		return fmt.Errorf("writing string for field t.Bar: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Foo (int64) (int64)
	if len("foo") > 8192 {
		return fmt.Errorf("string in field \"foo\" was too long")
	}
	if err := jw.WriteString(string("foo")); err != nil {
		return fmt.Errorf("writing string for field \"foo\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Foo)); err != nil {
		return fmt.Errorf("writing int64 for field t.Foo: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *TestCanonicalFieldOrder) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = TestCanonicalFieldOrder{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for TestCanonicalFieldOrder: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for TestCanonicalFieldOrder: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for TestCanonicalFieldOrder: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field TestCanonicalFieldOrder: string too large")
				}
				return fmt.Errorf("reading string for field TestCanonicalFieldOrder: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field TestCanonicalFieldOrder: %w", err)
			}
			switch name {

			// t.Drond (int64) (int64)
			case "Drond":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Drond: %w", err)
					}
					t.Drond = int64(nval)

				}

				// t.Zp (string) (string)
			case "ap":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Zp: string too long")
						}
						return fmt.Errorf("reading string for field t.Zp: %w", err)
					}
					t.Zp = string(sval)
				}

				// t.Bar (string) (string)
			case "beep":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Bar: string too long")
						}
						return fmt.Errorf("reading string for field t.Bar: %w", err)
					}
					t.Bar = string(sval)
				}

				// t.Foo (int64) (int64)
			case "foo":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Foo: %w", err)
					}
					t.Foo = int64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for TestCanonicalFieldOrder: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field TestCanonicalFieldOrder: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for TestCanonicalFieldOrder")
			}
		}
	}

	return nil
}
func (t *MapStringString) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Snorkleblump (map[string]string) (map)
	if len("Snorkleblump") > 8192 {
		return fmt.Errorf("string in field \"Snorkleblump\" was too long")
	}
	if err := jw.WriteString(string("Snorkleblump")); err != nil {
		return fmt.Errorf("writing string for field \"Snorkleblump\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Snorkleblump) > 4096 {
			return fmt.Errorf("cannot marshal t.Snorkleblump map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Snorkleblump: %w", err)
		}

		keys := make([]string, 0, len(t.Snorkleblump))
		for k := range t.Snorkleblump {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Snorkleblump: %w", err)
				}
			}
			v := t.Snorkleblump[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Snorkleblump: %w", err)
			}

			if len(v) > 8192 {
				return fmt.Errorf("string in field v was too long")
			}
			if err := jw.WriteString(string(v)); err != nil {
				return fmt.Errorf("writing string for field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Snorkleblump: %w", err)
		}
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *MapStringString) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = MapStringString{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for MapStringString: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for MapStringString: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for MapStringString: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field MapStringString: string too large")
				}
				return fmt.Errorf("reading string for field MapStringString: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field MapStringString: %w", err)
			}
			switch name {

			// t.Snorkleblump (map[string]string) (map)
			case "Snorkleblump":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Snorkleblump: %w", err)
				}

				t.Snorkleblump = map[string]string{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Snorkleblump: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Snorkleblump: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Snorkleblump: %w", err)
						}
						var v string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field v: string too long")
								}
								return fmt.Errorf("reading string for field v: %w", err)
							}
							v = string(sval)
						}
						t.Snorkleblump[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Snorkleblump: %w", err)
						}
						if close {
							break
						}
					}
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for MapStringString: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field MapStringString: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for MapStringString")
			}
		}
	}

	return nil
}
func (t *TestSliceNilPreserve) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Beep (int64) (int64)
	if len("Beep") > 8192 {
		return fmt.Errorf("string in field \"Beep\" was too long")
	}
	if err := jw.WriteString(string("Beep")); err != nil {
		return fmt.Errorf("writing string for field \"Beep\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Beep)); err != nil {
		return fmt.Errorf("writing int64 for field t.Beep: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cat (string) (string)
	if len("Cat") > 8192 {
		return fmt.Errorf("string in field \"Cat\" was too long")
	}
	if err := jw.WriteString(string("Cat")); err != nil {
		return fmt.Errorf("writing string for field \"Cat\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Cat) > 8192 {
		return fmt.Errorf("string in field t.Cat was too long")
	}
	if err := jw.WriteString(string(t.Cat)); err != nil {
		return fmt.Errorf("writing string for field t.Cat: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Not ([]uint64) (slice)
	if len("Not") > 8192 {
		return fmt.Errorf("string in field \"Not\" was too long")
	}
	if err := jw.WriteString(string("Not")); err != nil {
		return fmt.Errorf("writing string for field \"Not\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Not) > 8192 {
		return fmt.Errorf("slice value in field t.Not was too long")
	}

	if t.Not == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.Not: %w", err)
		}
	} else {

		if err := jw.WriteArrayOpen(); err != nil {
			return fmt.Errorf("writing array open for field t.Not: %w", err)
		}
		for i, v := range t.Not {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Not: %w", err)
				}
			}

			if err := jw.WriteUint64(uint64(v)); err != nil {
				return fmt.Errorf("writing uint64 for field v: %w", err)
			}

		}
		if err := jw.WriteArrayClose(); err != nil {
			return fmt.Errorf("writing array close for field t.Not: %w", err)
		}

	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.NotOther ([]uint8) (slice)
	if len("NotOther") > 8192 {
		return fmt.Errorf("string in field \"NotOther\" was too long")
	}
	if err := jw.WriteString(string("NotOther")); err != nil {
		return fmt.Errorf("writing string for field \"NotOther\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.NotOther) > 2097152 {
		return fmt.Errorf("byte array in field t.NotOther was too long")
	}

	if t.NotOther == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.NotOther: %w", err)
		}
	} else {

		if err := jw.WriteBytes(t.NotOther); err != nil {
			return fmt.Errorf("writing bytes for field t.NotOther: %w", err)
		}

	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Other ([]uint8) (slice)
	if len("Other") > 8192 {
		return fmt.Errorf("string in field \"Other\" was too long")
	}
	if err := jw.WriteString(string("Other")); err != nil {
		return fmt.Errorf("writing string for field \"Other\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Other) > 2097152 {
		return fmt.Errorf("byte array in field t.Other was too long")
	}

	if err := jw.WriteBytes(t.Other); err != nil {
		return fmt.Errorf("writing bytes for field t.Other: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Stuff ([]uint64) (slice)
	if len("Stuff") > 8192 {
		return fmt.Errorf("string in field \"Stuff\" was too long")
	}
	if err := jw.WriteString(string("Stuff")); err != nil {
		return fmt.Errorf("writing string for field \"Stuff\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Stuff) > 8192 {
		return fmt.Errorf("slice value in field t.Stuff was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Stuff: %w", err)
	}
	for i, v := range t.Stuff {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Stuff: %w", err)
			}
		}

		if err := jw.WriteUint64(uint64(v)); err != nil {
			return fmt.Errorf("writing uint64 for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Stuff: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *TestSliceNilPreserve) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = TestSliceNilPreserve{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for TestSliceNilPreserve: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for TestSliceNilPreserve: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for TestSliceNilPreserve: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field TestSliceNilPreserve: string too large")
				}
				return fmt.Errorf("reading string for field TestSliceNilPreserve: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field TestSliceNilPreserve: %w", err)
			}
			switch name {

			// t.Beep (int64) (int64)
			case "Beep":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Beep: %w", err)
					}
					t.Beep = int64(nval)

				}

				// t.Cat (string) (string)
			case "Cat":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Cat: string too long")
						}
						return fmt.Errorf("reading string for field t.Cat: %w", err)
					}
					t.Cat = string(sval)
				}

				// t.Not ([]uint64) (slice)
			case "Not":
				{

					open, err := jr.ReadArrayOpenOrNull()
					if err != nil {
						return fmt.Errorf("reading array open or null for field t.Not: %w", err)
					}
					if open {

						close, err := jr.PeekArrayClose()
						if err != nil {
							return fmt.Errorf("peeking array close for field t.Not: %w", err)
						}
						if close {
							if err := jr.ReadArrayClose(); err != nil {
								return fmt.Errorf("reading array close for field t.Not: %w", err)
							}

							t.Not = []uint64{}

						} else {
							for i := 0; i < 8192; i++ {
								item := make([]uint64, 1)
								{

									nval, err := jr.ReadNumberAsUint64()
									if err != nil {
										return fmt.Errorf("reading uint64 for field item[0]: %w", err)
									}
									item[0] = uint64(nval)

								}
								t.Not = append(t.Not, item[0])

								close, err := jr.ReadArrayCloseOrComma()
								if err != nil {
									return fmt.Errorf("reading array close or comma for field t.Not: %w", err)
								}
								if close {
									break
								}
								if i == 8192-1 {
									return fmt.Errorf("reading array for field t.Not: slice too large")
								}
							}
						}

					}

				}

				// t.NotOther ([]uint8) (slice)
			case "NotOther":

				{
					bval, err := jr.ReadBytesOrNull(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.NotOther: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.NotOther: %w", err)
					}
					if bval != nil {
						t.NotOther = []uint8(*bval)
					}
				}

				// t.Other ([]uint8) (slice)
			case "Other":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Other: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Other: %w", err)
					}
					if len(bval) > 0 {
						t.Other = []uint8(bval)
					}
				}

				// t.Stuff ([]uint64) (slice)
			case "Stuff":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Stuff: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Stuff: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Stuff: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]uint64, 1)
							{

								nval, err := jr.ReadNumberAsUint64()
								if err != nil {
									return fmt.Errorf("reading uint64 for field item[0]: %w", err)
								}
								item[0] = uint64(nval)

							}
							t.Stuff = append(t.Stuff, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Stuff: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Stuff: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for TestSliceNilPreserve: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field TestSliceNilPreserve: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for TestSliceNilPreserve")
			}
		}
	}

	return nil
}
func (t *StringPtrSlices) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.StringPtrs ([]*string) (slice)
	if len("StringPtrs") > 8192 {
		return fmt.Errorf("string in field \"StringPtrs\" was too long")
	}
	if err := jw.WriteString(string("StringPtrs")); err != nil {
		return fmt.Errorf("writing string for field \"StringPtrs\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.StringPtrs) > 8192 {
		return fmt.Errorf("slice value in field t.StringPtrs was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.StringPtrs: %w", err)
	}
	for i, v := range t.StringPtrs {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.StringPtrs: %w", err)
			}
		}
		if v == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("writing null for field v: %w", err)
			}
		} else {
			if len(*v) > 8192 {
				return fmt.Errorf("string in field v was too long")
			}
			if err := jw.WriteString(string(*v)); err != nil {
				return fmt.Errorf("writing string for field v: %w", err)
			}
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.StringPtrs: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Strings ([]string) (slice)
	if len("Strings") > 8192 {
		return fmt.Errorf("string in field \"Strings\" was too long")
	}
	if err := jw.WriteString(string("Strings")); err != nil {
		return fmt.Errorf("writing string for field \"Strings\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Strings) > 8192 {
		return fmt.Errorf("slice value in field t.Strings was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Strings: %w", err)
	}
	for i, v := range t.Strings {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Strings: %w", err)
			}
		}
		if len(v) > 8192 {
			return fmt.Errorf("string in field v was too long")
		}
		if err := jw.WriteString(string(v)); err != nil {
			return fmt.Errorf("writing string for field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Strings: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *StringPtrSlices) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = StringPtrSlices{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for StringPtrSlices: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for StringPtrSlices: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for StringPtrSlices: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field StringPtrSlices: string too large")
				}
				return fmt.Errorf("reading string for field StringPtrSlices: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field StringPtrSlices: %w", err)
			}
			switch name {

			// t.StringPtrs ([]*string) (slice)
			case "StringPtrs":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.StringPtrs: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.StringPtrs: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.StringPtrs: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]*string, 1)
							{
								sval, err := jr.ReadStringOrNull(8192)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading string or null for field item[0]: string too long")
									}
									return fmt.Errorf("reading string or null for field item[0]: %w", err)
								}
								if sval != nil {
									item[0] = (*string)(sval)
								}
							}
							t.StringPtrs = append(t.StringPtrs, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.StringPtrs: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.StringPtrs: slice too large")
							}
						}
					}

				}

				// t.Strings ([]string) (slice)
			case "Strings":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Strings: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Strings: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Strings: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]string, 1)
							{
								sval, err := jr.ReadString(8192)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading string for field item[0]: string too long")
									}
									return fmt.Errorf("reading string for field item[0]: %w", err)
								}
								item[0] = string(sval)
							}
							t.Strings = append(t.Strings, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Strings: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Strings: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for StringPtrSlices: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field StringPtrSlices: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for StringPtrSlices")
			}
		}
	}

	return nil
}
func (t *FieldNameOverlap) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.LongerNamedField (string) (string)
	if len("LongerNamedField") > 8192 {
		return fmt.Errorf("string in field \"LongerNamedField\" was too long")
	}
	if err := jw.WriteString(string("LongerNamedField")); err != nil {
		return fmt.Errorf("writing string for field \"LongerNamedField\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.LongerNamedField) > 8192 {
		return fmt.Errorf("string in field t.LongerNamedField was too long")
	}
	if err := jw.WriteString(string(t.LongerNamedField)); err != nil {
		return fmt.Errorf("writing string for field t.LongerNamedField: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Bar (string) (string)
	if len("beep") > 8192 {
		return fmt.Errorf("string in field \"beep\" was too long")
	}
	if err := jw.WriteString(string("beep")); err != nil {
		return fmt.Errorf("writing string for field \"beep\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Bar) > 8192 {
		return fmt.Errorf("string in field t.Bar was too long")
	}
	if err := jw.WriteString(string(t.Bar)); err != nil {
		return fmt.Errorf("writing string for field t.Bar: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Foo (int64) (int64)
	if len("foo") > 8192 {
		return fmt.Errorf("string in field \"foo\" was too long")
	}
	if err := jw.WriteString(string("foo")); err != nil {
		return fmt.Errorf("writing string for field \"foo\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Foo)); err != nil {
		return fmt.Errorf("writing int64 for field t.Foo: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *FieldNameOverlap) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = FieldNameOverlap{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for FieldNameOverlap: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for FieldNameOverlap: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for FieldNameOverlap: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field FieldNameOverlap: string too large")
				}
				return fmt.Errorf("reading string for field FieldNameOverlap: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field FieldNameOverlap: %w", err)
			}
			switch name {

			// t.LongerNamedField (string) (string)
			case "LongerNamedField":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.LongerNamedField: string too long")
						}
						return fmt.Errorf("reading string for field t.LongerNamedField: %w", err)
					}
					t.LongerNamedField = string(sval)
				}

				// t.Bar (string) (string)
			case "beep":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Bar: string too long")
						}
						return fmt.Errorf("reading string for field t.Bar: %w", err)
					}
					t.Bar = string(sval)
				}

				// t.Foo (int64) (int64)
			case "foo":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Foo: %w", err)
					}
					t.Foo = int64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for FieldNameOverlap: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field FieldNameOverlap: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for FieldNameOverlap")
			}
		}
	}

	return nil
}
