// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package testing

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *StrictFields) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := false

	// t.Nested (testing.StrictInner) (struct)
	if len("Nested") > 8192 {
		return fmt.Errorf("string in field \"Nested\" was too long")
	}
	if err := jw.WriteString(string("Nested")); err != nil {
		return fmt.Errorf("writing string for field \"Nested\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Nested.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Nested: %w", err)
	}
	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Bar (string) (string)
	if len("beep") > 8192 {
		return fmt.Errorf("string in field \"beep\" was too long")
	}
	if err := jw.WriteString(string("beep")); err != nil {
		return fmt.Errorf("writing string for field \"beep\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Bar) > 8192 {
		return fmt.Errorf("string in field t.Bar was too long")
	}
	if err := jw.WriteString(string(t.Bar)); err != nil {
		return fmt.Errorf("writing string for field t.Bar: %w", err)
	}
	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Foo (int64) (int64)
	if len("foo") > 8192 {
		return fmt.Errorf("string in field \"foo\" was too long")
	}
	if err := jw.WriteString(string("foo")); err != nil {
		return fmt.Errorf("writing string for field \"foo\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Foo)); err != nil {
		return fmt.Errorf("writing int64 for field t.Foo: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *StrictFields) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = StrictFields{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for StrictFields: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for StrictFields: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for StrictFields: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field StrictFields: string too large")
				}
				return fmt.Errorf("reading string for field StrictFields: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field StrictFields: %w", err)
			}
			switch name {

			// t.Nested (testing.StrictInner) (struct)
			case "Nested":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("peeking null for field t.Nested: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("reading null for field t.Nested: %w", err)
						}
					} else {
						t.Nested = new(StrictInner)
						if err := t.Nested.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Nested pointer: %w", err)
						}
					}
				}

				// t.Bar (string) (string)
			case "beep":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Bar: string too long")
						}
						return fmt.Errorf("reading string for field t.Bar: %w", err)
					}
					t.Bar = string(sval)
				}

				// t.Foo (int64) (int64)
			case "foo":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Foo: %w", err)
					}
					t.Foo = int64(nval)

				}
			default:
				return fmt.Errorf("unknown field %s for StrictFields", name)
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field StrictFields: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for StrictFields")
			}
		}
	}

	return nil
}
func (t *StrictInner) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Baz (uint64) (uint64)
	if len("Baz") > 8192 {
		return fmt.Errorf("string in field \"Baz\" was too long")
	}
	if err := jw.WriteString(string("Baz")); err != nil {
		return fmt.Errorf("writing string for field \"Baz\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Baz)); err != nil {
		return fmt.Errorf("writing uint64 for field t.Baz: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *StrictInner) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = StrictInner{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for StrictInner: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for StrictInner: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for StrictInner: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field StrictInner: string too large")
				}
				return fmt.Errorf("reading string for field StrictInner: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field StrictInner: %w", err)
			}
			switch name {

			// t.Baz (uint64) (uint64)
			case "Baz":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.Baz: %w", err)
					}
					t.Baz = uint64(nval)

				}
			default:
				return fmt.Errorf("unknown field %s for StrictInner", name)
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field StrictInner: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for StrictInner")
			}
		}
	}

	return nil
}
