// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package testing

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *LongString) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("LongString: %w", err)
	}

	// t.Val (string) (string)
	if len(t.Val) > 10000 {
		return fmt.Errorf("String in field t.Val was too long")
	}
	if err := jw.WriteString(string(t.Val)); err != nil {
		return fmt.Errorf("t.Val: %w", err)
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("LongString: %w", err)
	}
	return nil
}

func (t *LongString) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = LongString{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("LongString: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("LongString: %w", err)
	}
	if close {
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("LongString: %w", err)
		}
	} else {

		// t.Val (string) (string)

		{
			sval, err := jr.ReadString(10000)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("t.Val: string too long")
				}
				return fmt.Errorf("t.Val: %w", err)
			}
			t.Val = string(sval)
		}
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("LongString: %w", err)
		}
	}
	return nil
}
